import NextAuthProvider from "@/tools/providers/NextAuthProvider";
import "./globals.css";
import { PixieProvider } from "@/tools/providers/PixieProvider";
import Navbar from "@/tools/components/Navbar";
import Footer from "@/tools/components/Footer";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <NextAuthProvider>
        <PixieProvider>
          <head>
            <link rel="preconnect" href="https://fonts.googleapis.com" />
            <link
              rel="preconnect"
              href="https://fonts.gstatic.com"
              crossorigin
            />
            <link
              href="https://fonts.googleapis.com/css2?family=Cedarville+Cursive&family=Josefin+Sans:ital,wght@0,100..700;1,100..700&display=swap"
              rel="stylesheet"
            />
          </head>
          <body>
            <Navbar />
            {children}
            <Footer />
          </body>
        </PixieProvider>
      </NextAuthProvider>
    </html>
  );
}
